# Generated by Django 3.2.19 on 2024-09-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
