# Generated by Django 3.2.19 on 2024-04-19 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='draw_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
