# Generated by Django 3.2.19 on 2024-05-03 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20240423_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackpot',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jackpot',
            name='current_amount',
            field=models.DecimalField(decimal_places=20, max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='current_winning_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='next_amount',
            field=models.DecimalField(decimal_places=20, max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='next_winning_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
