# Generated by Django 3.2.19 on 2024-05-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20240503_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackpot',
            old_name='current_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='jackpot',
            old_name='current_winning_percentage',
            new_name='winning_percentage',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='next_amount',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='next_winning_percentage',
        ),
    ]
