# Generated by Django 3.2.19 on 2024-05-03 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20240503_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='ticket_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
