# Generated by Django 3.2.19 on 2024-05-03 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20240503_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpot',
            name='ticket_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='balance',
            field=models.DecimalField(decimal_places=20, max_digits=100, null=True),
        ),
    ]
