# Generated by Django 3.2.19 on 2024-05-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20240503_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='ticket',
        ),
        migrations.AddField(
            model_name='winner',
            name='participant_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='ticket_hash',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
