# Generated by Django 3.2.19 on 2024-07-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20240504_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackpot',
            name='amount',
        ),
    ]
