# Generated by Django 3.2.19 on 2024-07-25 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_remove_jackpot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='current_reward',
            field=models.DecimalField(decimal_places=20, max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='total_reward',
            field=models.DecimalField(decimal_places=20, max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
