# Generated by Django 3.2.19 on 2024-08-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20240801_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_balance',
            field=models.DecimalField(decimal_places=20, max_digits=100, null=True),
        ),
    ]
