# Generated by Django 3.2.19 on 2024-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0014_participant_current_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="winner",
            name="transaction",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
