# Generated by Django 3.2.19 on 2024-08-22 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_winner_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='reward_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
