# Generated by Django 3.2.19 on 2024-08-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0015_winner_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="current_balance",
        ),
    ]
