# Generated by Django 3.2.19 on 2024-08-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_jackpot_reward_percentage'),
        ('ticket', '0016_remove_participant_current_balance'),
    ]

    operations = [
    ]
