# Generated by Django 3.2.19 on 2024-08-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0017_merge_20240826_0047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winner",
            name="jackpot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winners",
                to="ticket.jackpot",
            ),
        ),
    ]
