# Generated by Django 3.2.19 on 2024-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_winner_closest_block_hash_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='distribute_status',
            field=models.BooleanField(default=False),
        ),
    ]
