# Generated by Django 3.2.19 on 2024-09-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_jackpot_distribute_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackpot',
            old_name='distribute_status',
            new_name='distributed_status',
        ),
    ]
