# Generated by Django 3.2.19 on 2024-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegator',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=20, max_digits=100)),
            ],
        ),
    ]
