# Generated by Django 3.2.19 on 2024-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegator',
            old_name='balance',
            new_name='total_balance',
        ),
        migrations.AddField(
            model_name='delegator',
            name='week_balance',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
