# Generated by Django 3.2.19 on 2024-07-25 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegator', '0002_auto_20240725_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegator',
            name='total_balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='delegator',
            name='week_balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
