# Generated by Django 3.2.19 on 2024-07-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegator', '0003_auto_20240725_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegator',
            old_name='week_balance',
            new_name='last_week_balance',
        ),
    ]
